### ISSUE TITLE
`platform.linux_distribution()` was removed in Python 3.8

### ISSUE THREAD

**Issue by tkkon** [flozz/rivalcfg#86]
Rivalcfg does not work with Python 3.8 under Arch Linux anymore. The reason probably is that `platform.linux_distribution()` was removed in Python 3.8. I get the following error:

```
[user@host bin]$ ./rivalcfg
Traceback (most recent call last):
  File "./rivalcfg", line 11, in <module>
    load_entry_point('rivalcfg==3.6.0', 'console_scripts', 'rivalcfg')()
  File "/home/testuser/.local/lib/python3.8/site-packages/rivalcfg/__main__.py", line 56, in main
    _print_debug_info()
  File "/home/testuser/.local/lib/python3.8/site-packages/rivalcfg/__main__.py", line 37, in _print_debug_info
    debug.log("Linux distribution: %s" % " ".join(platform.linux_distribution()))  # noqa
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

I removed these two lines from `__main__.py` and managed to get it to work again:
```
if platform.system() == "Linux":
        debug.log("Linux distribution: %s" % " ".join(platform.linux_distribution()))  # noqa
```

**Comment by flozz** [comment]
Nice catch, this function is marked as deprecated since **Python 3.5** and removed in **Python 3.8**: https://docs.python.org/3.7/library/platform.html#platform.linux_distribution 😅️

I will publish a fix on PYPI 🙂️

**Comment by flozz** [comment]
Fix released in **v3.6.1**, thanks

**Comment by B1tl0rd** [comment]
hi. alternative https://pypi.org/project/distro/

**Comment by flozz** [comment]
Yes I saw this in the Python doc, but I do not want to add a dependency just for printing the distro name when running the software in debug mode 🙂️
